# Generated by Django 4.2.6 on 2023-10-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_forum_api', '0004_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user_profile',
        ),
    ]
